### ISSUE TITLE
Add Python 3.4 branch

### ISSUE THREAD

**Issue by Hwesta** [pybee/Python-Linux-template#1]
The Briefcase tutorial [suggests Python 3.4](https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-0.html), but this template only has a branch for 3.5.  Add a 3.4 branch to the repo.

In the mean time, this workaround works

* Run `$ python setup.py linux`
* This generates an error:
```running linux
 * Writing application template...
Project template: https://github.com/pybee/Python-Linux-template.git
Traceback (most recent call last):
  File "/home/holly/.virtualenvs/briefcase-py34/lib/python3.4/site-packages/cookiecutter/vcs.py", line 129, in clone
    stderr=subprocess.STDOUT,
  File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['git', 'checkout', '3.4']' returned non-zero exit status 1
```
* Cookiecutter caches templates in `~/.cookiecutters`. Go to the project template at `~/.cookiecutters/Python-Linux-template`
* Git checkout 3.5

**Comment by freakboy3742** [comment]
This has now been resolved.
