### ISSUE TITLE
app would not start if formal_name contains spaces

### ISSUE THREAD

**Issue by denk-mal** [pybee/Python-Linux-template#7]
the APPDIR is not correctly resolved if the formal name (and therefore the script name) contains spaces. The line
`export APPDIR=$(dirname $(readlink -f "$0"))`
should be changed to
`export APPDIR=$(dirname "$(readlink -f "${0}")")`
(remark the quotes around the readlink command section.)

**Comment by LewisGaul** [comment]
PR at https://github.com/beeware/Python-Linux-template/pull/8

**Comment by freakboy3742** [comment]
Fixed in  755fd2b
